import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { CssBaseline, ThemeProvider, createTheme, Box, Drawer, List, ListItemButton, ListItemText, Typography, Grid, Paper, Chip, Stack, Button, TextField, LinearProgress, Divider } from '@mui/material';
import ReactECharts from 'echarts-for-react';
import { useEditor, EditorContent } from '@tiptap/react';
import StarterKit from '@tiptap/starter-kit';
import Image from '@tiptap/extension-image';
import Table from '@tiptap/extension-table';
import TableRow from '@tiptap/extension-table-row';
import TableCell from '@tiptap/extension-table-cell';
import TableHeader from '@tiptap/extension-table-header';
import { Canvas, Rect, Textbox } from 'fabric';
import { useRef } from 'react';
import './styles.css';

const modules = ['Dashboard','Calendar','Daily Ops','Trading Journal','Trade Review','Timeline','Notes','Screenshot Manager','Playbook','Statistics','Market Database','Reports','Settings'];
const sampleLevels = ['ONH 5428.25','ONL 5398.00','POC 5416.50','VAH 5422.75','VAL 5407.25','IB High pending'];

function Shell(){ const [active,setActive]=useState('Dashboard'); const [analytics,setAnalytics]=useState<any>(); useEffect(()=>{ window.tradingOS?.analytics().then(setAnalytics).catch(()=>setAnalytics({totalTrades:0,winRate:0,profitFactor:0,expectancy:0,averageR:0}));},[]); return <ThemeProvider theme={createTheme({palette:{mode:'dark',primary:{main:'#22c55e'},background:{default:'#070b12',paper:'#0d1420'}},typography:{fontFamily:'Inter,Segoe UI,Arial'}})}><CssBaseline/><Box sx={{display:'flex'}}><Drawer variant="permanent" PaperProps={{sx:{width:260,bgcolor:'#080d16',borderColor:'#1f2937'}}}><Box sx={{p:3}}><Typography variant="h5" fontWeight={800}>Trading OS</Typography><Typography color="text.secondary">Institutional Futures Journal</Typography></Box><List>{modules.map(m=><ListItemButton key={m} selected={active===m} onClick={()=>setActive(m)}><ListItemText primary={m}/></ListItemButton>)}</List></Drawer><Box component="main" sx={{ml:'260px',p:3,width:'calc(100% - 260px)'}}><Header active={active}/>{active==='Dashboard'&&<Dashboard analytics={analytics}/>} {active==='Daily Ops'&&<DailyOps/>}{active==='Trading Journal'&&<Journal/>}{active==='Timeline'&&<Timeline/>}{active==='Notes'&&<Notes/>}{active==='Screenshot Manager'&&<Screenshots/>}{active==='Statistics'&&<Statistics analytics={analytics}/>} {!['Dashboard','Daily Ops','Trading Journal','Timeline','Notes','Screenshot Manager','Statistics'].includes(active)&&<Module name={active}/>}</Box></Box></ThemeProvider> }
function Header({active}:{active:string}){return <Stack direction="row" justifyContent="space-between" alignItems="center" mb={3}><Box><Typography variant="h4" fontWeight={800}>{active}</Typography><Typography color="text.secondary">{new Date().toLocaleDateString(undefined,{weekday:'long',year:'numeric',month:'long',day:'numeric'})}</Typography></Box><Stack direction="row" gap={1}><Button variant="outlined" onClick={()=>window.tradingOS?.createBackup()}>Backup</Button><Button variant="contained">Global Search ⌘K</Button></Stack></Stack>}
function Card({title,children}:{title:string;children:React.ReactNode}){return <Paper className="panel"><Typography variant="overline" color="primary">{title}</Typography>{children}</Paper>}
function Dashboard({analytics}:{analytics:any}){return <Grid container spacing={2}><Grid item xs={12} md={8}><Card title="Today’s Command Center"><Grid container spacing={2}>{['Daily Bias: Neutral-Bullish','Market: Balance to imbalance','Open Trades: 0','Today PnL: $0','Execution Score: 0/100','Emotional State: Focused'].map(x=><Grid item xs={6} md={4} key={x}><Paper className="metric"><Typography>{x}</Typography></Paper></Grid>)}</Grid><Divider sx={{my:2}}/><Stack direction="row" gap={1} flexWrap="wrap">{sampleLevels.map(l=><Chip key={l} label={l} color="primary" variant="outlined"/> )}</Stack></Card></Grid><Grid item xs={12} md={4}><Card title="Performance Pulse"><Typography variant="h3">{Math.round((analytics?.winRate??0)*100)}%</Typography><Typography>Win rate</Typography><LinearProgress variant="determinate" value={(analytics?.profitFactor??0)*25} sx={{my:2}}/><Typography>Profit factor {(analytics?.profitFactor??0).toFixed(2)}</Typography></Card></Grid><Grid item xs={12}><Card title="Recent Journal Entries"><Typography color="text.secondary">No journal entries yet. Create a Daily Ops plan and attach trades, screenshots, mistakes, and emotions locally.</Typography></Card></Grid></Grid>}
function DailyOps(){ const fields=['Instrument','Market bias','Macro context','Economic events','VIX condition','Previous day analysis','Overnight analysis','Current inventory','Market structure','HVN / LVN / POC','VAH / VAL / Initial Balance','Support and resistance','Scenario 1 description, entry, confirmation, target, invalidation','Scenario 2 description, entry, confirmation, target, invalidation','Actual market type','Expected vs Actual']; return <Grid container spacing={2}>{fields.map(f=><Grid item xs={12} md={f.length>35?12:6} key={f}><TextField fullWidth multiline minRows={f.length>20?3:1} label={f}/></Grid>)}</Grid>}
function Journal(){return <Card title="Trade Ticket"><Grid container spacing={2}>{['Time','Instrument','Direction','Entry price','Exit price','Stop loss','Target','Quantity','Risk','Reward','R multiple','PnL','Commission','Session','Setup','Confidence score','Execution quality','Tags'].map(f=><Grid item xs={12} md={3} key={f}><TextField fullWidth label={f}/></Grid>)}</Grid></Card>}
function Timeline(){return <Card title="Chronological Market Tape"><Stack gap={2}>{['08:30 Market opened above value','09:15 Buyers failed to continue','09:30 Absorption detected','10:00 Entry executed'].map(e=><TextField key={e} defaultValue={e} fullWidth/>)}<Button>Add timestamped event</Button></Stack></Card>}
function Notes(){const editor=useEditor({extensions:[StarterKit,Image,Table.configure({resizable:true}),TableRow,TableHeader,TableCell],content:'<h2>Weekly Review</h2><p>Document ideas, research, market observations, and lessons.</p>'}); return <Card title="Rich Text Research Desk"><EditorContent editor={editor}/></Card>}
function Screenshots(){const ref=useRef<HTMLCanvasElement>(null); useEffect(()=>{ if(!ref.current) return; const c=new Canvas(ref.current,{backgroundColor:'#111827'}); c.add(new Rect({left:60,top:60,width:220,height:120,fill:'rgba(34,197,94,.15)',stroke:'#22c55e'})); c.add(new Textbox('Annotate entries, exits, absorption, and failed auctions',{left:80,top:95,width:420,fill:'#e5e7eb'})); return ()=>{c.dispose();};},[]); return <Card title="Screenshot Annotation"><Box className="dropzone">Drag and drop chart images here (stored locally)</Box><canvas ref={ref} width={900} height={360}/></Card>}
function Statistics({analytics}:{analytics:any}){const option=useMemo(()=>({xAxis:{type:'category',data:['Win Rate','Profit Factor','Expectancy','Avg R']},yAxis:{type:'value'},series:[{type:'bar',data:[(analytics?.winRate??0)*100,analytics?.profitFactor??0,analytics?.expectancy??0,analytics?.averageR??0]}]}),[analytics]); return <Card title="Advanced Analytics"><ReactECharts option={option}/><Typography>Total trades: {analytics?.totalTrades??0}</Typography></Card>}
function Module({name}:{name:string}){return <Card title={name}><Typography>This module is scaffolded with the local data model and ready for workflow-specific CRUD screens, filters, reports, imports, exports, and future integrations.</Typography></Card>}
createRoot(document.getElementById('root')!).render(<Shell/>);
